add missing math lib in compile/link check
while compiling lua232 in OpenEmbedded I've got this error:

lvm.c:(.text+0x166c): undefined reference to `floor'
lvm.c:(.text+0x1698): undefined reference to `pow'