bindings/lua: silence gcc 4.6 warning about unused but set variable
luars232.c: In function 'lua_port_read':
luars232.c:144:6: error: variable 'ret' set but not used [-Werror=unused-but-set-variable]

Which I don't clearly understand, but well...

Signed-off-by: Petr Štetiar <ynezz@true.cz>